# -*- coding: utf-8 -*-
PAGES = []

# ─────────────────────────── 9 · REVIEW DAY (all subjects) ───────────────────────────
PAGES.append(dict(
 file='09-review-day.html',
 title='Review Day',
 eyebrow='All subjects · mixed practice',
 palette=['#5a4bd1','#3d31a0','#e8e6fb','#d97a1e','#fbecd8',
          '#9d90f0','#c3baf8','#211b45','#eda65c','#3a2a12'],
 blurb='One page that mixes every lesson: English, Arabic, science, maps, time, money and the web.',
 blurb_ar='صفحة واحدة تجمع كل الدروس: الإنجليزية والعربية والعلوم والخرائط والوقت والمال والإنترنت.',
 learn_h='The whole week in one place',
 learn_p='Each part is a quick summary of one subject. Open it, listen, and check what you remember.',
 learn_ar='كل جزء ملخص سريع لمادة. افتحيه واستمعي وتأكدي مما تتذكرينه.',
 cards_h='Key facts from every subject',
 cards_p='One card, one fact. Say the answer first, then flip.',
 cards_ar='بطاقة واحدة لكل معلومة. قولي الإجابة أولاً ثم اقلبي البطاقة.',
 play_h='Which subject does it belong to?',
 play_p='Sort each fact into the subject it comes from.',
 play_ar='صنّفي كل معلومة حسب المادة التي جاءت منها.',
 parts=[
  dict(n='1', t='English — two meanings', ta='الإنجليزية — معنيان',
    html='<p><b>Denotative meaning</b> is the plain dictionary meaning of a word. <b>Connotative meaning</b> is the feeling and the memories the word brings.</p>'
         '<p>“Home is a place where a family lives” is denotative. “Home means love and warmth” is connotative.</p>',
    gloss='<p><b>المعنى الحرفي</b> هو معنى القاموس، و<b>المعنى المجازي</b> هو المشاعر والذكريات التي تثيرها الكلمة. «البيت مكان تعيش فيه الأسرة» حرفي، و«البيت يعني الحب والدفء» مجازي.</p>'),
  dict(n='2', t='Arabic — 28 letters', ta='العربية — ٢٨ حرفاً',
    html='<p>The Arabic alphabet has <b>28 letters</b> and is written from <b>right to left</b>.</p>'
         '<p>Dots tell similar letters apart: ب has one dot below, ت two above, ث three above.</p>',
    gloss='<p>الأبجدية العربية <b>٢٨ حرفاً</b> وتُكتب <b>من اليمين إلى اليسار</b>. والنقط تفرّق بين المتشابهات: الباء نقطة تحت، والتاء نقطتان فوق، والثاء ثلاث فوق.</p>'),
  dict(n='3', t='Science — how to think like a scientist', ta='العلوم — كيف تفكرين كعالمة',
    html='<p>The six basic skills are observing, measuring, classifying, inferring, predicting, and communicating.</p>'
         '<p>The scientific method starts with <b>ask a question</b> and ends with <b>report your findings</b>.</p>',
    gloss='<p>المهارات الست: الملاحظة والقياس والتصنيف والاستنتاج والتنبؤ والتواصل. ويبدأ المنهج العلمي بـ<b>طرح سؤال</b> وينتهي بـ<b>عرض النتائج</b>.</p>'),
  dict(n='4', t='Maps — lines on the globe', ta='الخرائط — خطوط الكرة',
    html='<p><b>Latitude</b> measures north and south. <b>Longitude</b> measures east and west.</p>'
         '<p>The <b>Equator</b> circles the middle of the Earth, and a full circle around the Earth is <b>360°</b>.</p>',
    gloss='<p><b>خطوط العرض</b> تقيس الشمال والجنوب، و<b>خطوط الطول</b> تقيس الشرق والغرب. و<b>خط الاستواء</b> يحيط بمنتصف الأرض، والدورة الكاملة <b>٣٦٠ درجة</b>.</p>'),
  dict(n='5', t='Time — hours and zones', ta='الوقت — ساعات ومناطق',
    html='<p>One hour is <b>60 minutes</b>, so 80 minutes is 1 hour and 20 minutes.</p>'
         '<p>The Earth turns once in <b>24 hours</b>, so there are <b>24 time zones</b>, each <b>1 hour</b> apart, starting at the Prime Meridian (UTC or GMT).</p>',
    gloss='<p>الساعة <b>٦٠ دقيقة</b>، فـ٨٠ دقيقة تساوي ساعة و٢٠ دقيقة. وتدور الأرض دورة كاملة في <b>٢٤ ساعة</b>، لذلك هناك <b>٢٤ منطقة زمنية</b> بين كل منها <b>ساعة</b>، تبدأ من خط جرينتش (UTC أو GMT).</p>'),
  dict(n='6', t='The web — search, browse, be kind', ta='الإنترنت — بحث وتصفح وأدب',
    html='<p>A <b>search engine</b> looks for information among millions of websites; a <b>browser</b> is the window you open to visit them.</p>'
         '<p><b>Netiquette</b> is good manners online: be polite, keep personal information private, and never be mean — that is <b>cyberbullying</b>.</p>',
    gloss='<p><b>محرك البحث</b> يبحث بين ملايين المواقع، و<b>المتصفح</b> هو النافذة التي تفتحينها لزيارتها. و<b>آداب الإنترنت</b> أن تكوني مهذبة وتحفظي معلوماتك الشخصية ولا تسيئي لأحد، فالإساءة المتكررة تسمى <b>التنمّر الإلكتروني</b>.</p>'),
  dict(n='7', t='Money — needs, wants, saving', ta='المال — احتياج ورغبة وادخار',
    html='<p>A <b>need</b> is something you must have; a <b>want</b> is something nice to have.</p>'
         '<p>If you spend everything, you save nothing. Pay for needs, then save, then enjoy your wants.</p>',
    gloss='<p><b>الاحتياج</b> ما لا بد منه، و<b>الرغبة</b> ما هو جميل لكن يمكن الاستغناء عنه. وإذا أنفقتِ كل شيء لن يتبقَّ ادخار: ادفعي للاحتياجات، ثم ادّخري، ثم استمتعي برغباتك.</p>'),
 ],
 cards=[
  dict(f='Denotative or connotative? “Rain is water falling from the sky.”', fa='حرفي أم مجازي؟', b='Denotative — it is the plain dictionary meaning.', ba='حرفي، لأنه معنى القاموس المباشر.'),
  dict(f='How many letters in the Arabic alphabet?', fa='كم حرفاً في العربية؟', b='28 letters, written right to left.', ba='٢٨ حرفاً، وتُكتب من اليمين إلى اليسار.'),
  dict(f='First step of the scientific method?', fa='أول خطوة في المنهج العلمي؟', b='Ask a question.', ba='طرح سؤال.'),
  dict(f='Latitude measures…', fa='خطوط العرض تقيس…', b='North and south.', ba='الشمال والجنوب.'),
  dict(f='Longitude measures…', fa='خطوط الطول تقيس…', b='East and west.', ba='الشرق والغرب.'),
  dict(f='How many minutes in an hour?', fa='كم دقيقة في الساعة؟', b='60 minutes.', ba='ستون دقيقة.'),
  dict(f='How many time zones on Earth?', fa='كم منطقة زمنية على الأرض؟', b='24 zones, each 1 hour apart.', ba='٢٤ منطقة، بين كل منها ساعة.'),
  dict(f='Who invented the World Wide Web?', fa='من اخترع الشبكة العنكبوتية؟', b='Tim Berners-Lee.', ba='تيم بيرنرز-لي.'),
  dict(f='What does the − symbol do in a search?', fa='ماذا تفعل علامة الناقص في البحث؟', b='It removes that word from the results.', ba='تستبعد تلك الكلمة من النتائج.'),
  dict(f='Being mean to someone online again and again is…', fa='الإساءة المتكررة لشخص على الإنترنت…', b='Cyberbullying.', ba='التنمّر الإلكتروني.'),
  dict(f='Need or want: transport to school?', fa='احتياج أم رغبة: مواصلات المدرسة؟', b='A need.', ba='احتياج.'),
  dict(f='Need or want: a new toy?', fa='احتياج أم رغبة: لعبة جديدة؟', b='A want.', ba='رغبة.'),
 ],
 game=dict(mode='sort',
   buckets=[dict(k='w', label='Web'), dict(k='s', label='Science'), dict(k='g', label='Geography'), dict(k='m', label='Money')],
   items=[
    dict(t='Netiquette means good manners online', ta='آداب الإنترنت = حسن السلوك على الشبكة', k='w'),
    dict(t='Observing, measuring, classifying', ta='الملاحظة والقياس والتصنيف', k='s'),
    dict(t='Latitude measures north and south', ta='خطوط العرض تقيس الشمال والجنوب', k='g'),
    dict(t='A want is nice but not necessary', ta='الرغبة جميلة لكنها ليست ضرورية', k='m'),
    dict(t='The address bar is part of a browser', ta='شريط العنوان جزء من المتصفح', k='w'),
    dict(t='A hypothesis is a guess you can test', ta='الفرضية تخمين يمكن اختباره', k='s'),
    dict(t='The Equator circles the middle of Earth', ta='خط الاستواء يحيط بمنتصف الأرض', k='g'),
    dict(t='Save first, then spend on wants', ta='ادّخري أولاً ثم أنفقي على الرغبات', k='m'),
   ]),
 quiz=[
  dict(q='The dictionary meaning of a word is called:', a='معنى الكلمة في القاموس يسمى:', o=['Connotative','Denotative','A synonym','A rhyme'], c=1),
  dict(q='How many letters are in the Arabic alphabet?', a='كم عدد حروف الأبجدية العربية؟', o=['26','28','30','24'], c=1),
  dict(q='Which is NOT one of the six basic science skills?', a='أي مما يلي ليس من المهارات الست الأساسية؟', o=['Observing','Classifying','Formulating a hypothesis','Predicting'], c=2),
  dict(q='Latitude lines measure:', a='خطوط العرض تقيس:', o=['North and south','East and west','Time','Height'], c=0),
  dict(q='100 minutes is the same as:', a='١٠٠ دقيقة تساوي:', o=['1 hour 40 minutes','1 hour 20 minutes','2 hours','1 hour 10 minutes'], c=0),
  dict(q='The Earth is divided into how many time zones?', a='إلى كم منطقة زمنية تنقسم الأرض؟', o=['12','24','36','60'], c=1),
  dict(q='A search engine is used to:', a='محرك البحث يُستخدم لـ:', o=['Look for information on the web','Print pages','Draw pictures','Play music only'], c=0),
  dict(q='Which part of the browser shows the page again?', a='أي جزء في المتصفح يعيد عرض الصفحة؟', o=['Home button','Refresh button','Tabs','Address bar'], c=1),
  dict(q='True or False: you should keep your telephone number private online.', a='صح أم خطأ: يجب أن تحفظي رقم هاتفك على الإنترنت.', o=['True','False'], c=0),
  dict(q='Which of these is a need?', a='أي مما يلي احتياج؟', o=['A waffle','Water','A toy','A fizzy drink'], c=1),
  dict(q='If you spend your whole allowance, how much do you save?', a='إذا أنفقتِ كل مصروفك، كم تدّخرين؟', o=['Nothing','Half','All of it','A quarter'], c=0),
  dict(q='UTC, the time at the Prime Meridian, is also called:', a='التوقيت عند خط جرينتش يسمى أيضاً:', o=['GMT','IDL','AM','PM'], c=0),
  dict(q='“Her smile was sunshine” uses which meaning?', a='«ابتسامتها كانت شمساً» تستخدم أي معنى؟', o=['Denotative','Connotative','Neither','Both equally'], c=1),
  dict(q='Constantly being mean to someone online is called:', a='الإساءة المستمرة لشخص على الإنترنت تسمى:', o=['Browsing','Netiquette','Cyberbullying','Searching'], c=2),
  dict(q='What is the last step of the scientific method?', a='ما آخر خطوة في المنهج العلمي؟', o=['Ask a question','Report your findings','Plan the experiment','Measure'], c=1),
 ]))
